<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 EDA | Librito de estadística</title>
  <meta name="description" content="Notas de métodos estadísticos: análisis exploratorio del precio de la vivienda en California." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 EDA | Librito de estadística" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notas de métodos estadísticos: análisis exploratorio del precio de la vivienda en California." />
  <meta name="github-repo" content="jscszn/libro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 EDA | Librito de estadística" />
  
  <meta name="twitter:description" content="Notas de métodos estadísticos: análisis exploratorio del precio de la vivienda en California." />
  

<meta name="author" content="jscszn" />


<meta name="date" content="2026-08-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Librito de estadística</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Contexto del problema</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> EDA</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#an%C3%A1lisis-exploratorio-de-median_house_value-target"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio de <code>median_house_value</code> (Target)</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#an%C3%A1lisis-de-las-variables-independientes-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>1.2</b> Análisis de las variables independientes (características)</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>1.3</b> Análisis exploratorio bivariado</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#relaciones-entre-las-propias-variables-independientes"><i class="fa fa-check"></i><b>1.3.1</b> Relaciones entre las propias variables independientes</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#paquete-ggally"><i class="fa fa-check"></i><b>1.4</b> Paquete GGally</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#correlaci%C3%B3n"><i class="fa fa-check"></i><b>1.5</b> Correlación</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#ingenier%C3%ADa-de-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>1.6</b> Ingeniería de características</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="intro.html"><a href="intro.html#sirven-las-nuevas-variables"><i class="fa fa-check"></i><b>1.6.1</b> ¿Sirven las nuevas variables?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Librito de estadística</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> EDA<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Carguemos las librerias</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="intro.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span>
<span id="cb1-3"><a href="intro.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-4"><a href="intro.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="intro.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="intro.html#cb2-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/housing.csv&quot;</span>)</span></code></pre></div>
<p>Muestrame las 5 primeras filas</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" tabindex="-1"></a><span class="fu">head</span>(data, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   longitude latitude housing_median_age total_rooms total_bedrooms population
## 1   -122.23    37.88                 41         880            129        322
## 2   -122.22    37.86                 21        7099           1106       2401
## 3   -122.24    37.85                 52        1467            190        496
## 4   -122.25    37.85                 52        1274            235        558
## 5   -122.25    37.85                 52        1627            280        565
##   households median_income median_house_value ocean_proximity
## 1        126        8.3252             452600        NEAR BAY
## 2       1138        8.3014             358500        NEAR BAY
## 3        177        7.2574             352100        NEAR BAY
## 4        219        5.6431             341300        NEAR BAY
## 5        259        3.8462             342200        NEAR BAY</code></pre>
<p>La estructura de los datos</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="intro.html#cb5-1" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20640 obs. of  10 variables:
##  $ longitude         : num  -122 -122 -122 -122 -122 ...
##  $ latitude          : num  37.9 37.9 37.9 37.9 37.9 ...
##  $ housing_median_age: num  41 21 52 52 52 52 52 52 42 52 ...
##  $ total_rooms       : num  880 7099 1467 1274 1627 ...
##  $ total_bedrooms    : num  129 1106 190 235 280 ...
##  $ population        : num  322 2401 496 558 565 ...
##  $ households        : num  126 1138 177 219 259 ...
##  $ median_income     : num  8.33 8.3 7.26 5.64 3.85 ...
##  $ median_house_value: num  452600 358500 352100 341300 342200 ...
##  $ ocean_proximity   : chr  &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; &quot;NEAR BAY&quot; ...</code></pre>
<p>Veamos si hay datos faltantes</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="intro.html#cb7-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="intro.html#cb7-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)),<span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_longitude NA_latitude NA_housing_median_age NA_total_rooms
## 1            0           0                     0              0
##   NA_total_bedrooms NA_population NA_households NA_median_income
## 1               207             0             0                0
##   NA_median_house_value NA_ocean_proximity
## 1                     0                  0</code></pre>
<p>Otra forma de detectar valores faltantes</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="intro.html#cb9-1" tabindex="-1"></a><span class="fu">missmap</span>(data)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/otraforma-1.png" alt="" width="672" /></p>
<p>Ahora, hagamos imputación de datos faltantes</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="intro.html#cb10-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="intro.html#cb10-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb10-3"><a href="intro.html#cb10-3" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric),</span>
<span id="cb10-4"><a href="intro.html#cb10-4" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.),<span class="fu">mean</span>(.,<span class="at">na.rm=</span><span class="cn">TRUE</span>),.)</span>
<span id="cb10-5"><a href="intro.html#cb10-5" tabindex="-1"></a>    )) <span class="ot">-&gt;</span> df</span></code></pre></div>
<p>Verifiquemos si tiene datos faltantes</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="intro.html#cb11-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="intro.html#cb11-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)),<span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_longitude NA_latitude NA_housing_median_age NA_total_rooms
## 1            0           0                     0              0
##   NA_total_bedrooms NA_population NA_households NA_median_income
## 1                 0             0             0                0
##   NA_median_house_value NA_ocean_proximity
## 1                     0                  0</code></pre>
<p>Vamos a convertir la variable ocean_proximity en un factor</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro.html#cb13-1" tabindex="-1"></a>df<span class="sc">$</span>ocean_proximity <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>ocean_proximity)</span></code></pre></div>
<div id="análisis-exploratorio-de-median_house_value-target" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Análisis exploratorio de <code>median_house_value</code> (Target)<a href="intro.html#an%C3%A1lisis-exploratorio-de-median_house_value-target" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Realicemos el resumen estadístico de la variable</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="intro.html#cb14-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(median_house_value),</span>
<span id="cb14-2"><a href="intro.html#cb14-2" tabindex="-1"></a>                 <span class="at">media =</span> <span class="fu">mean</span>(median_house_value),</span>
<span id="cb14-3"><a href="intro.html#cb14-3" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(median_house_value),</span>
<span id="cb14-4"><a href="intro.html#cb14-4" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(median_house_value),</span>
<span id="cb14-5"><a href="intro.html#cb14-5" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(median_house_value),</span>
<span id="cb14-6"><a href="intro.html#cb14-6" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(median_house_value,<span class="fl">0.25</span>),</span>
<span id="cb14-7"><a href="intro.html#cb14-7" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(median_house_value,<span class="fl">0.75</span>),</span>
<span id="cb14-8"><a href="intro.html#cb14-8" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(median_house_value),</span>
<span id="cb14-9"><a href="intro.html#cb14-9" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(median_house_value),</span>
<span id="cb14-10"><a href="intro.html#cb14-10" tabindex="-1"></a>                 <span class="at">asi =</span> <span class="fu">skewness</span>(median_house_value),</span>
<span id="cb14-11"><a href="intro.html#cb14-11" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(median_house_value)</span>
<span id="cb14-12"><a href="intro.html#cb14-12" tabindex="-1"></a>                 )</span></code></pre></div>
<pre><code>##       n    media       sd mediana    RIC     Q1     Q3 minimo maximo       asi
## 1 20640 206855.8 115395.6  179700 145125 119600 264725  14999 500001 0.9776922
##   curtosis
## 1   3.3275</code></pre>
<ul>
<li><code>n</code>: hay 20.640 bloques censales (recordemos que cada fila es un bloque, no una casa individual)</li>
<li><code>media</code>: en promedio, el valor mediano de la vivienda de un bloque es de 206.856 dólares americanos</li>
<li><code>mediana</code>: el 50% de los bloques tiene un valor mediano menor o igual a 179.700 dólares americanos</li>
<li><code>RIC</code>: el 50% central de los bloques se reparte a lo largo de una franja de 145.125 dólares de ancho</li>
<li><code>Q1</code>: el 25% de los bloques tiene un valor mediano menor o igual a 119.600 dólares americanos</li>
<li><code>Q3</code>: el 75% de los bloques tiene un valor mediano menor o igual a 264.725 dólares americanos</li>
<li><code>minimo</code>: el bloque más barato tiene un valor mediano de 14.999 dólares americanos</li>
<li><code>maximo</code>: el bloque más caro tiene un valor mediano de 500.001 dólares americanos</li>
<li><code>asi</code>: 0,98. Asimetría positiva moderada</li>
<li><code>curtosis</code>: 3,33. Es la curtosis de Pearson, que vale 3 en una normal, así que el exceso es de apenas 0,33</li>
</ul>
<p><strong>Interpretación.</strong> La media (206.856) supera a la mediana (179.700) en unos 27.000
dólares, y eso es justo lo que anticipa una asimetría positiva de 0,98: hay una
cola de bloques caros que estira el promedio hacia arriba, mientras la mayoría
se concentra en valores más bajos. La media, por tanto, <strong>no</strong> es un buen resumen
de “lo típico” en esta variable; la mediana describe mejor al bloque corriente.</p>
<p>La dispersión es muy alta: una desviación estándar de 115.396 dólares sobre una
media de 206.856 da un coeficiente de variación cercano al 56%. Dicho de otro
modo, el bloque más caro vale 33 veces lo que el más barato.</p>
<p>Un detalle que condiciona todo el análisis: el máximo es exactamente 500.001
dólares, un número demasiado redondo para ser casual. La variable está
<strong>censurada</strong>: todos los bloques que valían más de medio millón fueron
registrados con ese tope. Son 992 bloques, el 4,81% de la muestra.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="intro.html#cb16-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="intro.html#cb16-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb16-3"><a href="intro.html#cb16-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb16-4"><a href="intro.html#cb16-4" tabindex="-1"></a>                     <span class="at">binwidth =</span> <span class="dv">25000</span>,</span>
<span id="cb16-5"><a href="intro.html#cb16-5" tabindex="-1"></a>                      <span class="at">fill =</span> <span class="st">&quot;#ffc70f&quot;</span>,</span>
<span id="cb16-6"><a href="intro.html#cb16-6" tabindex="-1"></a>                      <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb16-7"><a href="intro.html#cb16-7" tabindex="-1"></a>                      <span class="at">alpha =</span> <span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb16-8"><a href="intro.html#cb16-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">linewidth =</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="intro.html#cb16-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&#39;Distribución del valor medio de las viviendas&#39;</span>,</span>
<span id="cb16-10"><a href="intro.html#cb16-10" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&#39;valor medio de la casa (USD)&#39;</span>,</span>
<span id="cb16-11"><a href="intro.html#cb16-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;densidad&#39;</span>)<span class="sc">+</span></span>
<span id="cb16-12"><a href="intro.html#cb16-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/histhousevalue-1.png" alt="" width="672" /></p>
<p>El histograma confirma lo que decían los estadísticos: la distribución es
unimodal, con el grueso de los bloques entre 100.000 y 250.000 dólares y una
cola derecha larga. Pero además hace visible algo que la tabla no mostraba: la
<strong>barra aislada en el extremo derecho</strong>, en 500.001 dólares. No es una cola que
decae suavemente, es un pico artificial creado por el tope de la codificación.
Esos 992 bloques no valen medio millón, valen <em>al menos</em> medio millón.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="intro.html#cb17-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span> median_house_value))<span class="sc">+</span></span>
<span id="cb17-3"><a href="intro.html#cb17-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb17-4"><a href="intro.html#cb17-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>)<span class="sc">+</span></span>
<span id="cb17-5"><a href="intro.html#cb17-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb17-6"><a href="intro.html#cb17-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="intro.html#cb17-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/boxplotvaluehouse-1.png" alt="" width="672" /></p>
<p>El boxplot cuenta la misma historia desde otro ángulo. El punto amarillo (la
media) queda a la derecha de la línea de la mediana, que es la firma gráfica de
la asimetría positiva. El bigote superior llega hasta 482.412 dólares
(Q3 + 1,5·RIC) y por encima quedan 1.071 bloques marcados como atípicos, de los
cuales 992 son exactamente el valor tope.</p>
<p>Conviene ser cuidadoso al llamarlos “atípicos”: no son errores de medición ni
casos raros que haya que eliminar, son barrios caros de California. La regla del
1,5·RIC los señala simplemente porque la distribución es asimétrica, y en una
distribución asimétrica esa regla siempre marca de más por el lado de la cola
larga.</p>
<p><strong>Implicaciones para el modelado.</strong> De este análisis salen tres decisiones que
habrá que tomar más adelante: (1) el tope de 500.001 sesga cualquier modelo que
prediga la parte alta del rango, y lo honesto es o bien excluir esos bloques o
bien usar un modelo que trate la censura explícitamente; (2) la asimetría
sugiere probar una transformación logarítmica de la respuesta; (3) la mediana y
el RIC son las medidas de resumen que deberíamos reportar, no la media y la
desviación estándar.</p>
</div>
<div id="análisis-de-las-variables-independientes-características" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Análisis de las variables independientes (características)<a href="intro.html#an%C3%A1lisis-de-las-variables-independientes-caracter%C3%ADsticas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="intro.html#cb18-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="intro.html#cb18-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>median_house_value) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="intro.html#cb18-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb18-4"><a href="intro.html#cb18-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb18-5"><a href="intro.html#cb18-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&#39;variable&#39;</span>,</span>
<span id="cb18-6"><a href="intro.html#cb18-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&#39;valor&#39;</span></span>
<span id="cb18-7"><a href="intro.html#cb18-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="intro.html#cb18-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span> </span>
<span id="cb18-9"><a href="intro.html#cb18-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(valor),</span>
<span id="cb18-10"><a href="intro.html#cb18-10" tabindex="-1"></a>                 <span class="at">media =</span> <span class="fu">mean</span>(valor),</span>
<span id="cb18-11"><a href="intro.html#cb18-11" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(valor),</span>
<span id="cb18-12"><a href="intro.html#cb18-12" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(valor),</span>
<span id="cb18-13"><a href="intro.html#cb18-13" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(valor),</span>
<span id="cb18-14"><a href="intro.html#cb18-14" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(valor,<span class="fl">0.25</span>),</span>
<span id="cb18-15"><a href="intro.html#cb18-15" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(valor,<span class="fl">0.75</span>),</span>
<span id="cb18-16"><a href="intro.html#cb18-16" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(valor),</span>
<span id="cb18-17"><a href="intro.html#cb18-17" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(valor),</span>
<span id="cb18-18"><a href="intro.html#cb18-18" tabindex="-1"></a>                 <span class="at">asi =</span> <span class="fu">skewness</span>(valor),</span>
<span id="cb18-19"><a href="intro.html#cb18-19" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor)</span>
<span id="cb18-20"><a href="intro.html#cb18-20" tabindex="-1"></a>                 )</span></code></pre></div>
<pre><code>## # A tibble: 8 × 12
##   variable      n   media     sd mediana    RIC      Q1      Q3   minimo  maximo
##   &lt;chr&gt;     &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 househol… 20640  500.   3.82e2  409    3.25e2  280     605       1      6082  
## 2 housing_… 20640   28.6  1.26e1   29    1.9 e1   18      37       1        52  
## 3 latitude  20640   35.6  2.14e0   34.3  3.78e0   33.9    37.7    32.5      42.0
## 4 longitude 20640 -120.   2.00e0 -118.   3.79e0 -122.   -118.   -124.     -114. 
## 5 median_i… 20640    3.87 1.90e0    3.53 2.18e0    2.56    4.74    0.500    15.0
## 6 populati… 20640 1425.   1.13e3 1166    9.38e2  787    1725       3     35682  
## 7 total_be… 20640  538.   4.19e2  438    3.46e2  297     643.      1      6445  
## 8 total_ro… 20640 2636.   2.18e3 2127    1.70e3 1448.   3148       2     39320  
## # ℹ 2 more variables: asi &lt;dbl&gt;, curtosis &lt;dbl&gt;</code></pre>
<p>El resumen estadístico de las 8 variables numéricas revela comportamientos muy distintos entre ellas. households y population presentan medias considerablemente superiores a sus medianas (499 vs 409 y 1425 vs 1166, respectivamente), junto con RIC elevados, lo que evidencia asimetría positiva y alta dispersión. total_rooms y total_bedrooms siguen el mismo patrón, con medias muy por encima de la mediana y desviaciones estándar enormes, confirmando lo observado en los boxplots. median_income muestra una distribución más equilibrada (media 3.87, mediana 3.53) con menor dispersión relativa, siendo la variable más homogénea del conjunto. housing_median_age es la más simétrica de todas, con media y mediana muy cercanas (~28.6 y 29) y el RIC más bajo. Finalmente, latitude y longitude corresponden a coordenadas geográficas, por lo que sus estadísticos describen la distribución espacial de los bloques censales en California, con poca variabilidad dado que el estado ocupa un rango geográfico acotado.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="intro.html#cb20-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="intro.html#cb20-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> housing_median_age))<span class="sc">+</span></span>
<span id="cb20-3"><a href="intro.html#cb20-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb20-4"><a href="intro.html#cb20-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>)<span class="sc">+</span></span>
<span id="cb20-5"><a href="intro.html#cb20-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb20-6"><a href="intro.html#cb20-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span> </span>
<span id="cb20-7"><a href="intro.html#cb20-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p1</span>
<span id="cb20-8"><a href="intro.html#cb20-8" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="intro.html#cb20-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> total_rooms))<span class="sc">+</span></span>
<span id="cb20-10"><a href="intro.html#cb20-10" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb20-11"><a href="intro.html#cb20-11" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>)<span class="sc">+</span></span>
<span id="cb20-12"><a href="intro.html#cb20-12" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb20-13"><a href="intro.html#cb20-13" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span> </span>
<span id="cb20-14"><a href="intro.html#cb20-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p2</span>
<span id="cb20-15"><a href="intro.html#cb20-15" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-16"><a href="intro.html#cb20-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> total_bedrooms))<span class="sc">+</span></span>
<span id="cb20-17"><a href="intro.html#cb20-17" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb20-18"><a href="intro.html#cb20-18" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>)<span class="sc">+</span></span>
<span id="cb20-19"><a href="intro.html#cb20-19" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb20-20"><a href="intro.html#cb20-20" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span> </span>
<span id="cb20-21"><a href="intro.html#cb20-21" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p3</span>
<span id="cb20-22"><a href="intro.html#cb20-22" tabindex="-1"></a></span>
<span id="cb20-23"><a href="intro.html#cb20-23" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/grafindep-1.png" alt="" width="672" /></p>
<p>housing_median_age presenta una distribución simétrica con mediana aproximada de 29 años y pocos valores atípicos, siendo la variable más estable de las tres. Por su parte, total_rooms y total_bedrooms muestran una marcada asimetría positiva: la caja está muy comprimida hacia valores bajos y existe una gran cantidad de outliers en la parte superior, lo que indica que la mayoría de los bloques tienen pocas habitaciones pero algunos presentan valores extremadamente altos. Dado este comportamiento, se recomienda aplicar una transformación logarítmica a estas dos variables antes de incluirlas en modelos estadísticos.</p>
<p>Veamos las tres variables que faltan por graficar:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro.html#cb21-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="intro.html#cb21-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> population))<span class="sc">+</span></span>
<span id="cb21-3"><a href="intro.html#cb21-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb21-4"><a href="intro.html#cb21-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb21-5"><a href="intro.html#cb21-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb21-6"><a href="intro.html#cb21-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="intro.html#cb21-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p4</span>
<span id="cb21-8"><a href="intro.html#cb21-8" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="intro.html#cb21-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> households))<span class="sc">+</span></span>
<span id="cb21-10"><a href="intro.html#cb21-10" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb21-11"><a href="intro.html#cb21-11" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb21-12"><a href="intro.html#cb21-12" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb21-13"><a href="intro.html#cb21-13" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="intro.html#cb21-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p5</span>
<span id="cb21-15"><a href="intro.html#cb21-15" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb21-16"><a href="intro.html#cb21-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y=</span> median_income))<span class="sc">+</span></span>
<span id="cb21-17"><a href="intro.html#cb21-17" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb21-18"><a href="intro.html#cb21-18" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb21-19"><a href="intro.html#cb21-19" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb21-20"><a href="intro.html#cb21-20" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>) <span class="sc">+</span></span>
<span id="cb21-21"><a href="intro.html#cb21-21" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> p6</span>
<span id="cb21-22"><a href="intro.html#cb21-22" tabindex="-1"></a></span>
<span id="cb21-23"><a href="intro.html#cb21-23" tabindex="-1"></a>p4 <span class="sc">+</span> p5 <span class="sc">+</span> p6</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/grafindep2-1.png" alt="" width="672" /></p>
<p><code>population</code> y <code>households</code> repiten el patrón de <code>total_rooms</code> y
<code>total_bedrooms</code>: caja aplastada contra el suelo y una nube de atípicos por
arriba (1.196 y 1.220 casos respectivamente). El caso extremo es un bloque con
35.682 habitantes, veinticinco veces la media. <code>median_income</code> es distinta: su
caja es simétrica y solo tiene 681 atípicos, todos por el lado alto, con un tope
llamativo en 15 (esta variable también está censurada, igual que la respuesta).</p>
<p>Los histogramas permiten ver la forma completa de cada distribución, no solo sus
cuartiles:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="intro.html#cb22-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="intro.html#cb22-2" tabindex="-1"></a>  <span class="fu">select</span>(housing_median_age, total_rooms, total_bedrooms,</span>
<span id="cb22-3"><a href="intro.html#cb22-3" tabindex="-1"></a>         population, households, median_income) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="intro.html#cb22-4" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb22-5"><a href="intro.html#cb22-5" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&#39;variable&#39;</span>, <span class="at">values_to =</span> <span class="st">&#39;valor&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="intro.html#cb22-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> valor))<span class="sc">+</span></span>
<span id="cb22-7"><a href="intro.html#cb22-7" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>)<span class="sc">+</span></span>
<span id="cb22-8"><a href="intro.html#cb22-8" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&#39;free&#39;</span>, <span class="at">ncol =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb22-9"><a href="intro.html#cb22-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&#39;frecuencia&#39;</span>)<span class="sc">+</span></span>
<span id="cb22-10"><a href="intro.html#cb22-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/histindep-1.png" alt="" width="672" /></p>
<p>Puestas una al lado de la otra se distinguen tres comportamientos:</p>
<ul>
<li><strong>Cuatro variables de tamaño</strong> (<code>total_rooms</code>, <code>total_bedrooms</code>, <code>population</code>,
<code>households</code>) con asimetrías positivas fuertes: entre 3,41 y 4,94, y curtosis
de hasta 76,5 en <code>population</code>. Todas describen lo mismo desde ángulos
distintos —cuán grande es el bloque— y todas piden transformación logarítmica.</li>
<li><strong><code>median_income</code></strong>, con asimetría 1,65: se aleja de la normal, pero mucho
menos, y el pico artificial del extremo derecho es el tope en 15.</li>
<li><strong><code>housing_median_age</code></strong>, con asimetría 0,06 y curtosis 2,20: casi simétrica y
algo más plana que una normal. Su pico en 52 años es otro tope de codificación:
todo lo construido antes de 1938 se registró como “52”.</li>
</ul>
<p>Las coordenadas geográficas merecen mirarse aparte, porque un histograma de
<code>latitude</code> no dice gran cosa. Graficadas juntas dibujan el mapa del estado:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="intro.html#cb23-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="intro.html#cb23-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude))<span class="sc">+</span></span>
<span id="cb23-3"><a href="intro.html#cb23-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">&#39;darkblue&#39;</span>, <span class="at">size =</span> <span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb23-4"><a href="intro.html#cb23-4" tabindex="-1"></a>  <span class="fu">coord_quickmap</span>()<span class="sc">+</span></span>
<span id="cb23-5"><a href="intro.html#cb23-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Longitud&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Latitud&#39;</span>)<span class="sc">+</span></span>
<span id="cb23-6"><a href="intro.html#cb23-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb23-7"><a href="intro.html#cb23-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">&#39;Distribución geográfica de los bloques censales&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/mapaunivar-1.png" alt="" width="672" /></p>
<p>Se reconoce la silueta de California y, sobre todo, las dos manchas densas que
corresponden al Área de la Bahía (arriba) y a Los Ángeles–San Diego (abajo).
Los bloques no están repartidos de forma uniforme por el territorio, sino
concentrados en las áreas metropolitanas de la costa: la bimodalidad de estas
dos variables es poblacional, no un defecto de los datos.</p>
<p>Ahora vemos la variable <code>ocean_proximity</code></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="intro.html#cb24-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="intro.html#cb24-2" tabindex="-1"></a>  <span class="fu">count</span>(ocean_proximity, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="intro.html#cb24-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>,<span class="dv">2</span>),</span>
<span id="cb24-4"><a href="intro.html#cb24-4" tabindex="-1"></a>                            <span class="at">Variable =</span> <span class="st">&#39;ocean_proximity&#39;</span>,</span>
<span id="cb24-5"><a href="intro.html#cb24-5" tabindex="-1"></a>                            <span class="at">Categoria =</span> <span class="fu">as.character</span>(ocean_proximity)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Variable,Categoria,n,Porcentaje) <span class="ot">-&gt;</span> tabla_ocean</span>
<span id="cb24-6"><a href="intro.html#cb24-6" tabindex="-1"></a>         </span>
<span id="cb24-7"><a href="intro.html#cb24-7" tabindex="-1"></a>         tabla_ocean</span></code></pre></div>
<pre><code>##          Variable  Categoria    n Porcentaje
## 1 ocean_proximity  &lt;1H OCEAN 9136      44.26
## 2 ocean_proximity     INLAND 6551      31.74
## 3 ocean_proximity     ISLAND    5       0.02
## 4 ocean_proximity   NEAR BAY 2290      11.09
## 5 ocean_proximity NEAR OCEAN 2658      12.88</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="intro.html#cb26-1" tabindex="-1"></a>tabla_ocean_b <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="intro.html#cb26-2" tabindex="-1"></a>  <span class="fu">count</span>(ocean_proximity, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="intro.html#cb26-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-4"><a href="intro.html#cb26-4" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb26-5"><a href="intro.html#cb26-5" tabindex="-1"></a>    <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb26-6"><a href="intro.html#cb26-6" tabindex="-1"></a>    </span>
<span id="cb26-7"><a href="intro.html#cb26-7" tabindex="-1"></a>tabla_ocean_b <span class="sc">%&gt;%</span> </span>
<span id="cb26-8"><a href="intro.html#cb26-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ocean_proximity, <span class="at">y =</span> n))<span class="sc">+</span></span>
<span id="cb26-9"><a href="intro.html#cb26-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb26-10"><a href="intro.html#cb26-10" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">4.5</span>)<span class="sc">+</span></span>
<span id="cb26-11"><a href="intro.html#cb26-11" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">&#39;Distribución de la variable ocean_proximity&#39;</span>)<span class="sc">+</span></span>
<span id="cb26-12"><a href="intro.html#cb26-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.15</span>)))<span class="sc">+</span></span>
<span id="cb26-13"><a href="intro.html#cb26-13" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/barrasocean-1.png" alt="" width="672" /></p>
</div>
<div id="análisis-exploratorio-bivariado" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Análisis exploratorio bivariado<a href="intro.html#an%C3%A1lisis-exploratorio-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="intro.html#cb27-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="intro.html#cb27-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> median_income, <span class="at">y =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb27-3"><a href="intro.html#cb27-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&#39;darkblue&#39;</span>)<span class="sc">+</span></span>
<span id="cb27-4"><a href="intro.html#cb27-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&#39;Valor medio de la viienda&#39;</span>,</span>
<span id="cb27-5"><a href="intro.html#cb27-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&#39;Ingreso medio&#39;</span>)<span class="sc">+</span></span>
<span id="cb27-6"><a href="intro.html#cb27-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb27-7"><a href="intro.html#cb27-7" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Dispersión entre ingreso medio y el valor medio de la vivienda&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/valorvsingreso-1.png" alt="" width="672" /></p>
<p>La relación es positiva y clara: a mayor ingreso mediano del bloque, mayor valor
de la vivienda. Es, con diferencia, la relación más fuerte del conjunto de datos.
En la nube se distinguen además tres artefactos:</p>
<ol style="list-style-type: decimal">
<li>La <strong>línea horizontal en 500.001</strong>, que ya conocemos: el tope de la respuesta.</li>
<li>Líneas horizontales más tenues alrededor de 450.000 y 350.000, que sugieren
algún redondeo en la codificación original.</li>
<li>La <strong>línea vertical en 15</strong>, el tope de <code>median_income</code>.</li>
</ol>
<p>La dispersión también crece con el ingreso (heterocedasticidad): entre los
bloques pobres los valores se agrupan, mientras que entre los ricos se abren
enormemente. Un modelo lineal simple violaría aquí el supuesto de varianza
constante.</p>
<p>Agrupando por quintiles de ingreso se ve la progresión sin la nube de puntos
encima:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="intro.html#cb28-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="intro.html#cb28-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">quintil =</span> <span class="fu">ntile</span>(median_income, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="intro.html#cb28-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(quintil), <span class="at">y =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb28-4"><a href="intro.html#cb28-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb28-5"><a href="intro.html#cb28-5" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb28-6"><a href="intro.html#cb28-6" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb28-7"><a href="intro.html#cb28-7" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>)<span class="sc">+</span></span>
<span id="cb28-8"><a href="intro.html#cb28-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Quintil de ingreso mediano&#39;</span>,</span>
<span id="cb28-9"><a href="intro.html#cb28-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Valor medio de la vivienda (USD)&#39;</span>)<span class="sc">+</span></span>
<span id="cb28-10"><a href="intro.html#cb28-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb28-11"><a href="intro.html#cb28-11" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Valor de la vivienda por quintil de ingreso&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/valorquintil-1.png" alt="" width="672" /></p>
<p>La mediana sube de forma monótona en cada escalón: 99.200 → 143.450 → 175.600 →
212.200 → 322.300 dólares. El salto del cuarto al quinto quintil (110.100
dólares) es más del doble que cualquier otro, así que la relación no es del todo
lineal: se acelera en la parte alta de la distribución de ingresos.</p>
<p>Ahora comparemos el valor medio de la vivienda según la aproximidad al oceano.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="intro.html#cb29-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="intro.html#cb29-2" tabindex="-1"></a>  <span class="fu">group_by</span>(ocean_proximity) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="intro.html#cb29-3" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(median_house_value),</span>
<span id="cb29-4"><a href="intro.html#cb29-4" tabindex="-1"></a>                 <span class="at">media =</span> <span class="fu">mean</span>(median_house_value),</span>
<span id="cb29-5"><a href="intro.html#cb29-5" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(median_house_value),</span>
<span id="cb29-6"><a href="intro.html#cb29-6" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(median_house_value),</span>
<span id="cb29-7"><a href="intro.html#cb29-7" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(median_house_value),</span>
<span id="cb29-8"><a href="intro.html#cb29-8" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(median_house_value,<span class="fl">0.25</span>),</span>
<span id="cb29-9"><a href="intro.html#cb29-9" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(median_house_value,<span class="fl">0.75</span>),</span>
<span id="cb29-10"><a href="intro.html#cb29-10" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(median_house_value),</span>
<span id="cb29-11"><a href="intro.html#cb29-11" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(median_house_value),</span>
<span id="cb29-12"><a href="intro.html#cb29-12" tabindex="-1"></a>                 <span class="at">asi =</span> <span class="fu">skewness</span>(median_house_value),</span>
<span id="cb29-13"><a href="intro.html#cb29-13" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(median_house_value)</span>
<span id="cb29-14"><a href="intro.html#cb29-14" tabindex="-1"></a>                 )</span></code></pre></div>
<pre><code>## # A tibble: 5 × 12
##   ocean_proximity     n  media     sd mediana    RIC     Q1     Q3 minimo maximo
##   &lt;fct&gt;           &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 &lt;1H OCEAN        9136 2.40e5 1.06e5  214850 125000 164100 289100  17500 500001
## 2 INLAND           6551 1.25e5 7.00e4  108500  71450  77500 148950  14999 500001
## 3 ISLAND              5 3.80e5 8.06e4  414700 150000 300000 450000 287500 450000
## 4 NEAR BAY         2290 2.59e5 1.23e5  233800 183200 162500 345700  22500 500001
## 5 NEAR OCEAN       2658 2.49e5 1.22e5  229450 172750 150000 322750  22500 500001
## # ℹ 2 more variables: asi &lt;dbl&gt;, curtosis &lt;dbl&gt;</code></pre>
<p>Veamos un gráfico de cajas y bigotes:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="intro.html#cb31-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="intro.html#cb31-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ocean_proximity, <span class="at">y =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb31-3"><a href="intro.html#cb31-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb31-4"><a href="intro.html#cb31-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb31-5"><a href="intro.html#cb31-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb31-6"><a href="intro.html#cb31-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>)<span class="sc">+</span></span>
<span id="cb31-7"><a href="intro.html#cb31-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Proximidad al océano&#39;</span>,</span>
<span id="cb31-8"><a href="intro.html#cb31-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Valor medio de la vivienda (USD)&#39;</span>)<span class="sc">+</span></span>
<span id="cb31-9"><a href="intro.html#cb31-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb31-10"><a href="intro.html#cb31-10" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Valor medio de la vivienda según la proximidad al océano&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/biboxplot-1.png" alt="" width="672" /></p>
<p>Aquí lo importante no es el orden de las cinco categorías, sino que <strong>una de
ellas se separa del resto</strong>. <code>INLAND</code> tiene una mediana de 108.500 dólares,
mientras que las tres categorías costeras masivas rondan todas los 215.000–235.000
(<code>&lt;1H OCEAN</code> 214.850, <code>NEAR OCEAN</code> 229.450, <code>NEAR BAY</code> 233.800) y son
prácticamente indistinguibles entre sí. Es decir: la variable no funciona como
una gradación de cercanía al mar, sino como una dicotomía interior/costa.</p>
<p><code>ISLAND</code> aparece como la categoría más cara (mediana 414.700), pero tiene solo
<strong>5 bloques</strong> de los 20.640. Con esa n, su caja no es una estimación en la que
se pueda confiar y conviene no sacar conclusiones de ella.</p>
<p>Veamos ahora la relación con la edad de las viviendas:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="intro.html#cb32-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="intro.html#cb32-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tramo =</span> <span class="fu">cut</span>(housing_median_age,</span>
<span id="cb32-3"><a href="intro.html#cb32-3" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">52</span>),</span>
<span id="cb32-4"><a href="intro.html#cb32-4" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&#39;1-10&#39;</span>, <span class="st">&#39;11-20&#39;</span>, <span class="st">&#39;21-30&#39;</span>, <span class="st">&#39;31-40&#39;</span>, <span class="st">&#39;41-52&#39;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="intro.html#cb32-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tramo, <span class="at">y =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb32-6"><a href="intro.html#cb32-6" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb32-7"><a href="intro.html#cb32-7" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb32-8"><a href="intro.html#cb32-8" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb32-9"><a href="intro.html#cb32-9" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>)<span class="sc">+</span></span>
<span id="cb32-10"><a href="intro.html#cb32-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Edad mediana de la vivienda (años)&#39;</span>,</span>
<span id="cb32-11"><a href="intro.html#cb32-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Valor medio de la vivienda (USD)&#39;</span>)<span class="sc">+</span></span>
<span id="cb32-12"><a href="intro.html#cb32-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb32-13"><a href="intro.html#cb32-13" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Valor de la vivienda por tramo de antigüedad&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/valorvsedad-1.png" alt="" width="672" /></p>
<p>El resultado es contraintuitivo: las viviendas <strong>más antiguas</strong> son las más
caras. La mediana pasa de 170.400 dólares en los bloques de 1 a 10 años a
197.500 en los de 41 a 52. No es que la vejez añada valor, es que los barrios
antiguos de California son los céntricos y costeros, mientras que la
construcción reciente está en la periferia y el interior. La edad está actuando
como un indicador indirecto de la ubicación.</p>
<p>La ubicación se ve mejor directamente sobre el mapa:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="intro.html#cb33-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="intro.html#cb33-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude, <span class="at">color =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb33-3"><a href="intro.html#cb33-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.7</span>)<span class="sc">+</span></span>
<span id="cb33-4"><a href="intro.html#cb33-4" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">&#39;plasma&#39;</span>, <span class="at">name =</span> <span class="st">&#39;Valor (USD)&#39;</span>)<span class="sc">+</span></span>
<span id="cb33-5"><a href="intro.html#cb33-5" tabindex="-1"></a>  <span class="fu">coord_quickmap</span>()<span class="sc">+</span></span>
<span id="cb33-6"><a href="intro.html#cb33-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Longitud&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Latitud&#39;</span>)<span class="sc">+</span></span>
<span id="cb33-7"><a href="intro.html#cb33-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb33-8"><a href="intro.html#cb33-8" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">&#39;Valor de la vivienda sobre el mapa de California&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/mapavalor-1.png" alt="" width="672" /></p>
<p>El patrón geográfico es rotundo: la franja costera se ilumina y el interior
(el Valle Central, el desierto del sureste) queda oscuro. Los dos focos más
caros coinciden con la Bahía de San Francisco y la costa de Los Ángeles. Esto
explica por qué <code>latitude</code> y <code>longitude</code> tienen correlaciones lineales bajas con
el precio pese a ser tan informativas: el efecto de la ubicación no es
“más al norte, más caro”, sino “más cerca del mar, más caro”, y eso ninguna
recta sobre una sola coordenada lo captura.</p>
<div id="relaciones-entre-las-propias-variables-independientes" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Relaciones entre las propias variables independientes<a href="intro.html#relaciones-entre-las-propias-variables-independientes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hasta aquí hemos comparado cada característica con la respuesta. Igual de
importante es ver cómo se relacionan entre sí, porque variables que miden lo
mismo causan problemas al modelar:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="intro.html#cb34-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="intro.html#cb34-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> households, <span class="at">y =</span> total_rooms))<span class="sc">+</span></span>
<span id="cb34-3"><a href="intro.html#cb34-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">&#39;darkblue&#39;</span>, <span class="at">size =</span> <span class="fl">0.7</span>)<span class="sc">+</span></span>
<span id="cb34-4"><a href="intro.html#cb34-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&#39;darkred&#39;</span>)<span class="sc">+</span></span>
<span id="cb34-5"><a href="intro.html#cb34-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Número de hogares&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Número total de habitaciones&#39;</span>)<span class="sc">+</span></span>
<span id="cb34-6"><a href="intro.html#cb34-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb34-7"><a href="intro.html#cb34-7" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Hogares frente a habitaciones totales&#39;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="notasmetodos_files/figure-html/roomsvshouseholds-1.png" alt="" width="672" /></p>
<p>Los puntos caen casi sobre una recta. Es lo esperable —más hogares implican más
habitaciones— pero significa que ambas variables aportan casi la misma
información. Las cuatro variables de tamaño (<code>total_rooms</code>, <code>total_bedrooms</code>,
<code>population</code>, <code>households</code>) forman un bloque redundante que trataremos en la
sección de correlación.</p>
<p>Por último, conviene comprobar si el efecto de la ubicación es independiente del
ingreso o si ambas cosas van juntas:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="intro.html#cb36-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="intro.html#cb36-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ocean_proximity, <span class="at">y =</span> median_income))<span class="sc">+</span></span>
<span id="cb36-3"><a href="intro.html#cb36-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb36-4"><a href="intro.html#cb36-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb36-5"><a href="intro.html#cb36-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb36-6"><a href="intro.html#cb36-6" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>)<span class="sc">+</span></span>
<span id="cb36-7"><a href="intro.html#cb36-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Proximidad al océano&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Ingreso mediano&#39;</span>)<span class="sc">+</span></span>
<span id="cb36-8"><a href="intro.html#cb36-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb36-9"><a href="intro.html#cb36-9" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Ingreso mediano según la proximidad al océano&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/ingresovsoceano-1.png" alt="" width="672" /></p>
<p>Los bloques del interior son también, en promedio, más pobres. La correlación
entre “estar en la costa” y el ingreso mediano es de 0,24: existe, pero es
moderada. Eso quiere decir que ubicación e ingreso <strong>no</strong> son la misma variable
disfrazada y que cada una aporta información propia sobre el precio.</p>
</div>
</div>
<div id="paquete-ggally" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Paquete GGally<a href="intro.html#paquete-ggally" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="intro.html#cb37-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="intro.html#cb37-2" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
<p><img src="notasmetodos_files/figure-html/ggaly-1.png" alt="" width="672" /></p>
</div>
<div id="correlación" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Correlación<a href="intro.html#correlaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><code>ggpairs()</code> nos ha dado todos los coeficientes de golpe, pero en una rejilla
difícil de leer. Vamos a extraer solo la matriz de correlaciones y a
representarla como un mapa de calor:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="intro.html#cb39-1" tabindex="-1"></a>matriz_cor <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="intro.html#cb39-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="intro.html#cb39-3" tabindex="-1"></a>  <span class="fu">cor</span>()</span>
<span id="cb39-4"><a href="intro.html#cb39-4" tabindex="-1"></a></span>
<span id="cb39-5"><a href="intro.html#cb39-5" tabindex="-1"></a>matriz_cor <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="intro.html#cb39-6" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-7"><a href="intro.html#cb39-7" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">&#39;variable1&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-8"><a href="intro.html#cb39-8" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>variable1,</span>
<span id="cb39-9"><a href="intro.html#cb39-9" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&#39;variable2&#39;</span>, <span class="at">values_to =</span> <span class="st">&#39;r&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="intro.html#cb39-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> variable1, <span class="at">y =</span> variable2, <span class="at">fill =</span> r))<span class="sc">+</span></span>
<span id="cb39-11"><a href="intro.html#cb39-11" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">&#39;white&#39;</span>)<span class="sc">+</span></span>
<span id="cb39-12"><a href="intro.html#cb39-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(r, <span class="dv">2</span>)), <span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb39-13"><a href="intro.html#cb39-13" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low =</span> <span class="st">&quot;#5c1427&quot;</span>, <span class="at">mid =</span> <span class="st">&#39;white&#39;</span>, <span class="at">high =</span> <span class="st">&quot;#008B8B&quot;</span>,</span>
<span id="cb39-14"><a href="intro.html#cb39-14" tabindex="-1"></a>                       <span class="at">midpoint =</span> <span class="dv">0</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb39-15"><a href="intro.html#cb39-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>)<span class="sc">+</span></span>
<span id="cb39-16"><a href="intro.html#cb39-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb39-17"><a href="intro.html#cb39-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb39-18"><a href="intro.html#cb39-18" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span><span class="st">&#39;Matriz de correlaciones de Pearson&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/matrizcorr-1.png" alt="" width="768" /></p>
<p>Y ordenamos las correlaciones con la variable respuesta:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="intro.html#cb40-1" tabindex="-1"></a>matriz_cor[, <span class="st">&#39;median_house_value&#39;</span>] <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="intro.html#cb40-2" tabindex="-1"></a>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="intro.html#cb40-3" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## median_house_value      median_income        total_rooms housing_median_age 
##              1.000              0.688              0.134              0.106 
##         households     total_bedrooms         population          longitude 
##              0.066              0.049             -0.025             -0.046 
##           latitude 
##             -0.144</code></pre>
<p><strong>Interpretación.</strong> La matriz deja ver tres cosas.</p>
<p><em>Primera: una sola variable predice de verdad.</em> <code>median_income</code> correlaciona
0,688 con el precio. La siguiente en la lista, <code>total_rooms</code>, se queda en 0,134,
y de ahí para abajo todo es ruido (<code>households</code> 0,066, <code>total_bedrooms</code> 0,049,
<code>population</code> −0,025). Por sí sola, la recta del ingreso explica el 47% de la
varianza del precio.</p>
<p><em>Segunda: hay un bloque de variables redundantes.</em> <code>total_rooms</code>,
<code>total_bedrooms</code>, <code>population</code> y <code>households</code> correlacionan entre sí entre 0,86
y 0,97 (<code>households</code> con <code>total_bedrooms</code> llega a 0,97). Si se regresa
<code>households</code> sobre las otras tres se obtiene un R² de 0,963: la variable es
prácticamente una combinación lineal de sus compañeras. Meterlas las cuatro en
un modelo lineal produce <strong>multicolinealidad severa</strong>, con coeficientes
inestables y de signo impredecible. Hay que quedarse con una, combinarlas, o
transformarlas en razones, que es lo que haremos en la sección siguiente.</p>
<p><em>Tercera: las correlaciones bajas no significan variables inútiles.</em> <code>latitude</code>
marca −0,144 y <code>longitude</code> −0,046, pero el mapa de la sección anterior mostraba
que la ubicación importa muchísimo. Lo que ocurre es que la correlación de
Pearson solo mide relación <strong>lineal</strong>, y el efecto geográfico tiene forma de
“cerca de la costa”, no de “hacia el norte”. Entre ellas, además, correlacionan
−0,92, porque California es un estado alargado en diagonal: al avanzar hacia el
norte se avanza también hacia el oeste.</p>
<p>Una advertencia sobre el 0,688 del ingreso: está inflado por el tope de la
respuesta. Si excluimos los 992 bloques censurados, la correlación baja a 0,647.</p>
</div>
<div id="ingeniería-de-características" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Ingeniería de características<a href="intro.html#ingenier%C3%ADa-de-caracter%C3%ADsticas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El análisis anterior nos deja un diagnóstico claro: tenemos cuatro variables de
tamaño redundantes entre sí y poco correlacionadas con el precio. El problema es
que <code>total_rooms</code> mide <strong>cuán grande es el bloque</strong>, no cuán buenas son sus
viviendas. Un bloque con 5.000 habitaciones puede ser un barrio de mansiones o
un conjunto de pisos pequeños; el número absoluto no distingue.</p>
<p>La solución es convertir esos totales en <strong>razones per cápita</strong>, que sí describen
la calidad de la vivienda:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="intro.html#cb42-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="intro.html#cb42-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-3"><a href="intro.html#cb42-3" tabindex="-1"></a>    <span class="at">rooms_per_household      =</span> total_rooms <span class="sc">/</span> households,</span>
<span id="cb42-4"><a href="intro.html#cb42-4" tabindex="-1"></a>    <span class="at">bedrooms_per_room        =</span> total_bedrooms <span class="sc">/</span> total_rooms,</span>
<span id="cb42-5"><a href="intro.html#cb42-5" tabindex="-1"></a>    <span class="at">population_per_household =</span> population <span class="sc">/</span> households,</span>
<span id="cb42-6"><a href="intro.html#cb42-6" tabindex="-1"></a>    <span class="at">costa =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(ocean_proximity <span class="sc">==</span> <span class="st">&#39;INLAND&#39;</span>, <span class="st">&#39;interior&#39;</span>, <span class="st">&#39;costa&#39;</span>))</span>
<span id="cb42-7"><a href="intro.html#cb42-7" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> dfe</span></code></pre></div>
<ul>
<li><code>rooms_per_household</code>: habitaciones por hogar. Mide el <strong>tamaño de la vivienda
típica</strong> del bloque.</li>
<li><code>bedrooms_per_room</code>: qué proporción de las habitaciones son dormitorios. Mide
el <strong>tipo de vivienda</strong>: un valor bajo indica casas con salones, estudios y
espacios comunes amplios; uno alto, viviendas pequeñas donde casi todo es
dormitorio.</li>
<li><code>population_per_household</code>: personas por hogar. Mide el <strong>hacinamiento</strong>.</li>
<li><code>costa</code>: recoge la dicotomía interior/costa que descubrimos en el boxplot de
<code>ocean_proximity</code>, en lugar de las cinco categorías originales.</li>
</ul>
<p>Veamos su resumen estadístico:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="intro.html#cb43-1" tabindex="-1"></a>dfe <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="intro.html#cb43-2" tabindex="-1"></a>  <span class="fu">select</span>(rooms_per_household, bedrooms_per_room, population_per_household) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="intro.html#cb43-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb43-4"><a href="intro.html#cb43-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&#39;variable&#39;</span>, <span class="at">values_to =</span> <span class="st">&#39;valor&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="intro.html#cb43-5" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="intro.html#cb43-6" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">mean</span>(valor),</span>
<span id="cb43-7"><a href="intro.html#cb43-7" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(valor),</span>
<span id="cb43-8"><a href="intro.html#cb43-8" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(valor),</span>
<span id="cb43-9"><a href="intro.html#cb43-9" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(valor),</span>
<span id="cb43-10"><a href="intro.html#cb43-10" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(valor),</span>
<span id="cb43-11"><a href="intro.html#cb43-11" tabindex="-1"></a>            <span class="at">asi =</span> <span class="fu">skewness</span>(valor))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   variable                 media mediana      sd minimo  maximo   asi
##   &lt;chr&gt;                    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 bedrooms_per_room        0.214   0.203  0.0698 0.0459    3.49  9.28
## 2 population_per_household 3.07    2.82  10.4    0.692  1243.   97.6 
## 3 rooms_per_household      5.43    5.23   2.47   0.846   142.   20.7</code></pre>
<p>Y su distribución (recortando las colas extremas para poder ver algo):</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="intro.html#cb45-1" tabindex="-1"></a>dfe <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="intro.html#cb45-2" tabindex="-1"></a>  <span class="fu">select</span>(rooms_per_household, bedrooms_per_room, population_per_household) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="intro.html#cb45-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb45-4"><a href="intro.html#cb45-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&#39;variable&#39;</span>, <span class="at">values_to =</span> <span class="st">&#39;valor&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="intro.html#cb45-5" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="intro.html#cb45-6" tabindex="-1"></a>  <span class="fu">filter</span>(valor <span class="sc">&lt;=</span> <span class="fu">quantile</span>(valor, <span class="fl">0.99</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb45-7"><a href="intro.html#cb45-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> valor))<span class="sc">+</span></span>
<span id="cb45-8"><a href="intro.html#cb45-8" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">color =</span> <span class="st">&#39;white&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>)<span class="sc">+</span></span>
<span id="cb45-9"><a href="intro.html#cb45-9" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&#39;free&#39;</span>, <span class="at">ncol =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb45-10"><a href="intro.html#cb45-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&#39;frecuencia&#39;</span>,</span>
<span id="cb45-11"><a href="intro.html#cb45-11" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">&#39;Se ha recortado el 1% superior de cada variable para la visualización&#39;</span>)<span class="sc">+</span></span>
<span id="cb45-12"><a href="intro.html#cb45-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/histnuevas-1.png" alt="" width="672" /></p>
<p>Los valores centrales son razonables y fáciles de leer: la vivienda típica
californiana de 1990 tenía <strong>5,2 habitaciones</strong>, de las cuales alrededor del
<strong>20% eran dormitorios</strong>, y la habitaban <strong>2,8 personas</strong>.</p>
<p>Los máximos, en cambio, delatan datos problemáticos: 141,9 habitaciones por
hogar, 1.243 personas por hogar y una proporción de dormitorios de 3,49 (un
valor <strong>imposible</strong>, porque los dormitorios son un subconjunto de las
habitaciones). Son bloques con poquísimos hogares donde la razón se dispara, o
directamente errores. En total, 69 bloques superan las 20 habitaciones por hogar,
37 superan las 10 personas por hogar y 10 tienen más dormitorios que
habitaciones. Antes de modelar habría que revisarlos o recortarlos.</p>
<div id="sirven-las-nuevas-variables" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> ¿Sirven las nuevas variables?<a href="intro.html#sirven-las-nuevas-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="intro.html#cb46-1" tabindex="-1"></a>dfe <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="intro.html#cb46-2" tabindex="-1"></a>  <span class="fu">select</span>(median_house_value, rooms_per_household, bedrooms_per_room,</span>
<span id="cb46-3"><a href="intro.html#cb46-3" tabindex="-1"></a>         population_per_household, total_rooms, total_bedrooms,</span>
<span id="cb46-4"><a href="intro.html#cb46-4" tabindex="-1"></a>         population, households) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="intro.html#cb46-5" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="intro.html#cb46-6" tabindex="-1"></a>  .[, <span class="st">&#39;median_house_value&#39;</span>] <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="intro.html#cb46-7" tabindex="-1"></a>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="intro.html#cb46-8" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       median_house_value      rooms_per_household              total_rooms 
##                    1.000                    0.152                    0.134 
##               households           total_bedrooms population_per_household 
##                    0.066                    0.049                   -0.024 
##               population        bedrooms_per_room 
##                   -0.025                   -0.220</code></pre>
<p>Comparando cada razón con el total del que procede:</p>
<table>
<thead>
<tr class="header">
<th>Variable original</th>
<th>r</th>
<th>Nueva variable</th>
<th>r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>total_rooms</code></td>
<td>0,134</td>
<td><code>rooms_per_household</code></td>
<td><strong>0,152</strong></td>
</tr>
<tr class="even">
<td><code>total_bedrooms</code></td>
<td>0,049</td>
<td><code>bedrooms_per_room</code></td>
<td><strong>−0,220</strong></td>
</tr>
<tr class="odd">
<td><code>population</code></td>
<td>−0,025</td>
<td><code>population_per_household</code></td>
<td>−0,024</td>
</tr>
</tbody>
</table>
<p><code>bedrooms_per_room</code> es el caso más llamativo: pasa de una variable inservible
(0,049) a la <strong>mejor característica estructural del conjunto</strong> (−0,220), y
además con un signo interpretable: cuantos más dormitorios por habitación,
más barata la vivienda. Tiene sentido, porque una proporción baja de dormitorios
implica casas con espacios adicionales, y eso es un lujo.</p>
<p><code>population_per_household</code> parece no aportar nada (−0,024), pero es un
espejismo causado por los valores extremos: su correlación de Spearman —que usa
rangos y por tanto es inmune a ellos— es de <strong>−0,257</strong>, y si recortamos el 1%
superior, la de Pearson sube a <strong>−0,28</strong>. La variable sí informa: a más
hacinamiento, menor precio. Solo hay que limpiarla antes.</p>
<p>Este contraste entre Pearson y Spearman merece mirarse en todas las variables:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="intro.html#cb48-1" tabindex="-1"></a>dfe <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="intro.html#cb48-2" tabindex="-1"></a>  <span class="fu">select</span>(median_house_value, median_income, rooms_per_household,</span>
<span id="cb48-3"><a href="intro.html#cb48-3" tabindex="-1"></a>         bedrooms_per_room, population_per_household, total_rooms,</span>
<span id="cb48-4"><a href="intro.html#cb48-4" tabindex="-1"></a>         housing_median_age, latitude) <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="intro.html#cb48-5" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">method =</span> <span class="st">&#39;spearman&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="intro.html#cb48-6" tabindex="-1"></a>  .[, <span class="st">&#39;median_house_value&#39;</span>] <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="intro.html#cb48-7" tabindex="-1"></a>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-8"><a href="intro.html#cb48-8" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       median_house_value            median_income      rooms_per_household 
##                    1.000                    0.677                    0.263 
##              total_rooms       housing_median_age                 latitude 
##                    0.206                    0.075                   -0.166 
## population_per_household        bedrooms_per_room 
##                   -0.257                   -0.330</code></pre>
<p>Por rangos, las tres razones nuevas ocupan los puestos 2, 3 y 4 del ranking,
justo detrás del ingreso. Ninguna variable original lo conseguía.</p>
<p>Veamos gráficamente la más prometedora:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="intro.html#cb50-1" tabindex="-1"></a>dfe <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="intro.html#cb50-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">quintil =</span> <span class="fu">ntile</span>(bedrooms_per_room, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="intro.html#cb50-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(quintil), <span class="at">y =</span> median_house_value))<span class="sc">+</span></span>
<span id="cb50-4"><a href="intro.html#cb50-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9a37cc&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#5c1427&quot;</span>,</span>
<span id="cb50-5"><a href="intro.html#cb50-5" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb50-6"><a href="intro.html#cb50-6" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb50-7"><a href="intro.html#cb50-7" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;yellow&#39;</span>)<span class="sc">+</span></span>
<span id="cb50-8"><a href="intro.html#cb50-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Quintil de proporción de dormitorios&#39;</span>,</span>
<span id="cb50-9"><a href="intro.html#cb50-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Valor medio de la vivienda (USD)&#39;</span>)<span class="sc">+</span></span>
<span id="cb50-10"><a href="intro.html#cb50-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb50-11"><a href="intro.html#cb50-11" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span><span class="st">&#39;Valor de la vivienda por proporción de dormitorios&#39;</span>)</span></code></pre></div>
<p><img src="notasmetodos_files/figure-html/bprquintil-1.png" alt="" width="672" /></p>
<p>El primer quintil (menos del 16,9% de dormitorios) tiene una mediana de 281.550
dólares, muy por encima de los demás. A partir del segundo quintil la relación
se aplana en torno a los 150.000–180.000. O sea: la variable no discrimina a lo
largo de todo su recorrido, sino que <strong>identifica un grupo caro</strong> en el extremo
bajo. Esto sugiere usarla en tramos, no como variable continua.</p>
<p>Por último, comprobemos cuánta varianza explica cada conjunto de variables:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="intro.html#cb51-1" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="cf">function</span>(formula) <span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(formula, <span class="at">data =</span> dfe))<span class="sc">$</span>r.squared, <span class="dv">3</span>)</span>
<span id="cb51-2"><a href="intro.html#cb51-2" tabindex="-1"></a></span>
<span id="cb51-3"><a href="intro.html#cb51-3" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb51-4"><a href="intro.html#cb51-4" tabindex="-1"></a>  <span class="at">modelo =</span> <span class="fu">c</span>(<span class="st">&#39;Solo ingreso&#39;</span>,</span>
<span id="cb51-5"><a href="intro.html#cb51-5" tabindex="-1"></a>             <span class="st">&#39;Ingreso + variables originales&#39;</span>,</span>
<span id="cb51-6"><a href="intro.html#cb51-6" tabindex="-1"></a>             <span class="st">&#39;Ingreso + razones nuevas + edad&#39;</span>,</span>
<span id="cb51-7"><a href="intro.html#cb51-7" tabindex="-1"></a>             <span class="st">&#39;Ingreso + razones nuevas + edad + costa&#39;</span>,</span>
<span id="cb51-8"><a href="intro.html#cb51-8" tabindex="-1"></a>             <span class="st">&#39;Todas las variables&#39;</span>),</span>
<span id="cb51-9"><a href="intro.html#cb51-9" tabindex="-1"></a>  <span class="at">R2 =</span> <span class="fu">c</span>(</span>
<span id="cb51-10"><a href="intro.html#cb51-10" tabindex="-1"></a>    <span class="fu">r2</span>(median_house_value <span class="sc">~</span> median_income),</span>
<span id="cb51-11"><a href="intro.html#cb51-11" tabindex="-1"></a>    <span class="fu">r2</span>(median_house_value <span class="sc">~</span> median_income <span class="sc">+</span> total_rooms <span class="sc">+</span> total_bedrooms <span class="sc">+</span></span>
<span id="cb51-12"><a href="intro.html#cb51-12" tabindex="-1"></a>         population <span class="sc">+</span> households <span class="sc">+</span> housing_median_age),</span>
<span id="cb51-13"><a href="intro.html#cb51-13" tabindex="-1"></a>    <span class="fu">r2</span>(median_house_value <span class="sc">~</span> median_income <span class="sc">+</span> rooms_per_household <span class="sc">+</span></span>
<span id="cb51-14"><a href="intro.html#cb51-14" tabindex="-1"></a>         bedrooms_per_room <span class="sc">+</span> population_per_household <span class="sc">+</span> housing_median_age),</span>
<span id="cb51-15"><a href="intro.html#cb51-15" tabindex="-1"></a>    <span class="fu">r2</span>(median_house_value <span class="sc">~</span> median_income <span class="sc">+</span> rooms_per_household <span class="sc">+</span></span>
<span id="cb51-16"><a href="intro.html#cb51-16" tabindex="-1"></a>         bedrooms_per_room <span class="sc">+</span> population_per_household <span class="sc">+</span> housing_median_age <span class="sc">+</span></span>
<span id="cb51-17"><a href="intro.html#cb51-17" tabindex="-1"></a>         costa),</span>
<span id="cb51-18"><a href="intro.html#cb51-18" tabindex="-1"></a>    <span class="fu">r2</span>(median_house_value <span class="sc">~</span> median_income <span class="sc">+</span> total_rooms <span class="sc">+</span> total_bedrooms <span class="sc">+</span></span>
<span id="cb51-19"><a href="intro.html#cb51-19" tabindex="-1"></a>         population <span class="sc">+</span> households <span class="sc">+</span> housing_median_age <span class="sc">+</span> rooms_per_household <span class="sc">+</span></span>
<span id="cb51-20"><a href="intro.html#cb51-20" tabindex="-1"></a>         bedrooms_per_room <span class="sc">+</span> population_per_household <span class="sc">+</span> costa)</span>
<span id="cb51-21"><a href="intro.html#cb51-21" tabindex="-1"></a>  )</span>
<span id="cb51-22"><a href="intro.html#cb51-22" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##   modelo                                     R2
##   &lt;chr&gt;                                   &lt;dbl&gt;
## 1 Solo ingreso                            0.473
## 2 Ingreso + variables originales          0.566
## 3 Ingreso + razones nuevas + edad         0.531
## 4 Ingreso + razones nuevas + edad + costa 0.6  
## 5 Todas las variables                     0.634</code></pre>
<p>Conviene leer esta tabla con honestidad. El ingreso solo ya explica el 47,3% de
la varianza. Añadir las variables originales sube al 56,6%, y sustituirlas por
las razones nuevas da 53,1%: <strong>algo menos</strong>. Las razones ganan variable a
variable, pero las cuatro originales juntas, aun siendo redundantes, capturan
información de tamaño que las razones descartan.</p>
<p>La aportación grande viene de otro lado: añadir <code>costa</code> al modelo de razones lo
lleva de 53,1% a <strong>60,0%</strong>. Una sola variable binaria, construida a partir de un
patrón que vimos en un boxplot, aporta más que todo el trabajo con razones. Y el
modelo completo llega al 63,4%, apenas dos décimas por encima del que usa las
originales más <code>costa</code> (63,2%).</p>
<p><strong>Conclusión.</strong> Las razones per cápita no son un atajo para mejorar el R², sino
para obtener un modelo <strong>interpretable</strong>: sustituyen cuatro variables
correlacionadas al 0,9 —cuyos coeficientes serían inestables e ilegibles— por
tres medidas con significado propio (tamaño de vivienda, tipo de vivienda,
hacinamiento) y correlaciones entre sí mucho más bajas. A igualdad aproximada de
capacidad predictiva, eso es lo que interesa en un modelo explicativo. Y el
hallazgo más rentable del capítulo no salió de ninguna transformación
sofisticada, sino de mirar un gráfico de cajas y notar que <code>INLAND</code> se separaba
del resto.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jscszn/libro/edit/main/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
